development:
  adapter: postgresql
  database: rssreader
  pool: 5
  encoding: unicode
  username: mike
  password: pass001

test:
  adapter: sqlite3
  dbfile: db/test.sqlite3

#TODO add details about production database
production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: 
  pool: 5
  username: 
  password: 
  socket: /var/run/mysqld/mysqld.sock
